"""
sites.py — Registry of all known Sri Lankan book selling websites.

Each entry contains:
  - name        : display name
  - url         : base URL
  - platform    : woocommerce | opencart | magento | shopify | custom
  - language    : primary language(s) sold
  - specialty   : what the site is known for
  - shop_paths  : where the product listings live
  - product_url_must_contain : path fragment that identifies a product URL
  - product_url_skip         : fragments to always skip
  - selectors   : site-specific CSS overrides (merged with global defaults)
  - notes       : human-readable notes / caveats
  - active      : False if site is known to block bots or is down
"""

SITES: list[dict] = [
    # ──────────────────────────────────────────────────────────────────────────
    # WOOCOMMERCE SITES
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": "rasakatha",
        "name": "Rasakatha.lk",
        "url": "https://rasakatha.lk",
        "platform": "woocommerce",
        "language": "Sinhala",
        "specialty": "Sinhala novels, self-help, spiritual (1400+ books)",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/books/",
        "product_url_skip": ["/product-category/", "/cart", "/wishlist", "/tag/"],
        "selectors": {
            "name":  "h1.product_title",
            "price": ".summary .price",
            "desc":  ".woocommerce-product-details__short-description",
            "image": ".woocommerce-product-gallery__image img",
            "sku":   ".sku",
            "cat":   ".posted_in a",
        },
        "active": True,
        "notes": "Largest Sinhala book store. Pagination via ?page=N",
    },
    {
        "id": "books_lk",
        "name": "Books.lk",
        "url": "https://books.lk",
        "platform": "woocommerce",
        "language": "English, Sinhala, Tamil",
        "specialty": "English & Sinhala books, second-hand, CDs",
        "shop_paths": ["/product-category/books/", "/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart", "/tag/", "/my-account"],
        "selectors": {
            "name":  "h1.product_title",
            "price": "p.price",
            "desc":  ".woocommerce-product-details__short-description",
            "image": ".woocommerce-product-gallery__image img",
        },
        "active": True,
        "notes": "WooCommerce. Also sells magazines and Blu-Ray.",
    },
    {
        "id": "pothak",
        "name": "Pothak.lk",
        "url": "https://pothak.lk",
        "platform": "woocommerce",
        "language": "Sinhala, English",
        "specialty": "Sinhala books, children's books, Soviet Russian reprints",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart", "/tag/"],
        "selectors": {
            "name":  "h1.product_title",
            "price": ".summary .price",
            "image": ".woocommerce-product-gallery__image img",
        },
        "active": True,
        "notes": "Standard WooCommerce. Good collection of children's books.",
    },
    {
        "id": "viyathbooks",
        "name": "ViyathBooks.lk",
        "url": "https://www.viyathbooks.lk",
        "platform": "woocommerce",
        "language": "English, Sinhala",
        "specialty": "International and local books, up to 20% discounts",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Standard WooCommerce setup.",
    },
    {
        "id": "bargainbooks",
        "name": "BargainBooks.lk",
        "url": "https://bargainbooks.lk",
        "platform": "woocommerce",
        "language": "English",
        "specialty": "Discounted fiction, non-fiction, thriller, self-help",
        "shop_paths": ["/shop/", "/books/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Focus on discounted/clearance books.",
    },
    {
        "id": "bookshop_lk",
        "name": "BookShop.lk",
        "url": "https://bookshop.lk",
        "platform": "woocommerce",
        "language": "Sinhala",
        "specialty": "School books, past papers, Nananimihira, Sinhala novels",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Strong in educational books and school stationery.",
    },
    {
        "id": "jeyabook",
        "name": "JeyaBook Centre",
        "url": "https://jeyabookcentre.com",
        "platform": "woocommerce",
        "language": "English, Tamil, Sinhala",
        "specialty": "Medical, academic, fiction, multi-language",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Known for medical and academic books.",
    },
    {
        "id": "mdgunasena",
        "name": "MD Gunasena",
        "url": "https://mdgunasena.com",
        "platform": "woocommerce",
        "language": "Sinhala, English",
        "specialty": "Sri Lanka's oldest bookstore (est. 1913), publisher & retailer",
        "shop_paths": ["/shop/", "/product-category/books/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "110+ year old institution. 16 physical stores island-wide.",
    },
    {
        "id": "bookrack",
        "name": "BookRack.lk",
        "url": "https://bookrack.lk",
        "platform": "woocommerce",
        "language": "Sinhala, English",
        "specialty": "General books online store",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "",
    },

    # ──────────────────────────────────────────────────────────────────────────
    # OPENCART SITES
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": "kbooks",
        "name": "KBooks.lk",
        "url": "https://www.kbooks.lk",
        "platform": "opencart",
        "language": "Sinhala, English, Tamil",
        "specialty": "Largest Sinhala translation collection, multi-language",
        "shop_paths": ["/novels", "/short_stories", "/poetry", "/translations",
                       "/children's_books", "/educational", "/non_fiction"],
        "product_url_must_contain": "product_id=",
        "product_url_skip": ["/category", "/account", "/cart", "/checkout"],
        "selectors": {
            "name":  "#product-name, h1.page-header",
            "price": ".price-new, .product-price",
            "desc":  "#tab-description, .product-description",
            "image": "#image-main img, .product-image img",
        },
        "active": True,
        "notes": "OpenCart. URLs use ?route=product/product&product_id=NNN",
    },
    {
        "id": "booksbay",
        "name": "BooksBay.lk",
        "url": "https://www.booksbay.lk",
        "platform": "opencart",
        "language": "Sinhala",
        "specialty": "Sinhala novels, translations, educational, religious",
        "shop_paths": [
            "/index.php?route=product/category&path=20",   # Novels
            "/index.php?route=product/category&path=18",   # Translations
            "/index.php?route=product/category&path=25",   # Children's
            "/index.php?route=product/category&path=24",   # Educational
        ],
        "product_url_must_contain": "route=product/product",
        "product_url_skip": ["/account", "/cart", "/checkout", "/category"],
        "selectors": {
            "name":  "h1",
            "price": ".price-new, .product-price",
            "desc":  "#tab-description",
            "image": "#image img, .product-image img",
        },
        "active": True,
        "notes": "OpenCart. Also has 2025 award-nominated books.",
    },

    # ──────────────────────────────────────────────────────────────────────────
    # MAGENTO SITES
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": "grantha",
        "name": "Grantha.lk",
        "url": "https://grantha.lk",
        "platform": "magento",
        "language": "Sinhala",
        "specialty": "Largest Sinhala book catalogue — novels, educational, religious",
        "shop_paths": ["/all-categories.html", "/books.html", "/"],
        "product_url_must_contain": ".html",
        "product_url_skip": ["/customer", "/cart", "/checkout", "/search",
                              "/catalogsearch", ".html/list", "-category"],
        "selectors": {
            "name":  "h1.page-title span, span[itemprop='name']",
            "price": ".product-info-price .price-wrapper",
            "desc":  ".product.attribute.description .value, [itemprop='description']",
            "image": ".gallery-placeholder img, .fotorama__img",
        },
        "active": True,
        "notes": "Magento 2. JavaScript-heavy; some pages may need Playwright.",
    },

    # ──────────────────────────────────────────────────────────────────────────
    # CUSTOM / UNKNOWN PLATFORMS
    # ──────────────────────────────────────────────────────────────────────────
    {
        "id": "bookolog",
        "name": "Bookolog.lk",
        "url": "https://bookolog.lk",
        "platform": "custom",
        "language": "English",
        "specialty": "English books — fiction, self-help, business (277 books)",
        "shop_paths": ["/books"],
        "product_url_must_contain": "/books/",
        "product_url_skip": ["/cart", "/login", "/register", "/blog",
                              "/authors", "/categories", "/new-arrivals",
                              "/combo-offers", "/kids", "/track"],
        "selectors": {
            "name":  "h1.product-title, h1",
            "price": ".product-price, .price",
            "desc":  ".product-description, .description",
            "image": ".product-image img, .book-cover img",
        },
        "active": True,
        "notes": "Custom Laravel/PHP stack. Pagination via ?page=N.",
    },
    {
        "id": "slbooks",
        "name": "SLBooks.lk",
        "url": "https://slbooks.lk",
        "platform": "custom",
        "language": "English, Sinhala",
        "specialty": "Academic, Cambridge, award-winning literary works",
        "shop_paths": ["/books/", "/shop/", "/"],
        "product_url_must_contain": "/book/",
        "product_url_skip": ["/cart", "/account", "/checkout"],
        "selectors": {},
        "active": True,
        "notes": "Focuses on Cambridge University Press and academic titles.",
    },
    {
        "id": "sarasavi",
        "name": "Sarasavi.lk",
        "url": "https://www.sarasavi.lk",
        "platform": "custom",
        "language": "Sinhala, English",
        "specialty": "Major chain bookstore — fiction, educational, religious",
        "shop_paths": ["/books/", "/shop/", "/products/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/category/", "/cart", "/account"],
        "selectors": {},
        "active": True,
        "notes": "Leading physical + online chain. May return empty pages.",
    },
    {
        "id": "booxworm",
        "name": "BooxWorm.lk",
        "url": "https://booxworm.lk",
        "platform": "shopify",
        "language": "English",
        "specialty": "Bestsellers, self-help, biography, business",
        "shop_paths": ["/collections/all", "/collections/books"],
        "product_url_must_contain": "/products/",
        "product_url_skip": ["/collections/", "/pages/", "/account", "/cart"],
        "selectors": {
            "name":  "h1.product__title, h1.product-single__title",
            "price": ".product__price, .price",
            "desc":  ".product__description, .product-single__description",
            "image": ".product__media img, .product-single__photo img",
        },
        "active": True,
        "notes": "Shopify store. Also writes book buying guides on their blog.",
    },
    {
        "id": "vijithayapa",
        "name": "Vijitha Yapa",
        "url": "https://www.vijithayapa.com",
        "platform": "woocommerce",
        "language": "Sinhala, English",
        "specialty": "Major chain — fiction, non-fiction, stationery",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": False,
        "notes": "Returns 403 for automated requests. Try with a browser.",
    },
    {
        "id": "jumpbooks",
        "name": "JumpBooks.lk",
        "url": "https://jumpbooks.lk",
        "platform": "shopify",
        "language": "English, Sinhala",
        "specialty": "Fiction, non-fiction, children's, free delivery over Rs 6500",
        "shop_paths": ["/collections/all"],
        "product_url_must_contain": "/products/",
        "product_url_skip": ["/collections/", "/pages/", "/account", "/cart"],
        "selectors": {
            "name":  "h1.product__title, h1.product-single__title",
            "price": ".product__price, .price__current",
            "desc":  ".product__description",
            "image": ".product__media img",
        },
        "active": False,
        "notes": "Returns 403 for automated requests. Shopify CDN.",
    },
    {
        "id": "makeenbooks",
        "name": "Makeen Books",
        "url": "https://makeenbooks.com",
        "platform": "custom",
        "language": "English, Sinhala",
        "specialty": "Millions of books — physical + online delivery",
        "shop_paths": ["/books/", "/shop/", "/products/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Large catalogue. Platform to be confirmed on first run.",
    },
    {
        "id": "samudrabooks",
        "name": "Samudra Book Shop",
        "url": "https://samudrabooks.com",
        "platform": "custom",
        "language": "Sinhala",
        "specialty": "Educational, novels, historical, psychological books",
        "shop_paths": ["/shop/", "/books/", "/products/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Physical stores + online. Platform to be confirmed.",
    },
    {
        "id": "bookmania",
        "name": "BookMania.lk",
        "url": "https://bookmania.lk",
        "platform": "woocommerce",
        "language": "Sinhala, English, Tamil",
        "specialty": "Sinhala, English, Tamil books + stationery",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": False,
        "notes": "Returns 403. May require browser-based scraping.",
    },
    {
        "id": "bookstore_lk2",
        "name": "BookStore.lk",
        "url": "https://bookstore.lk",
        "platform": "woocommerce",
        "language": "Sinhala, English",
        "specialty": "Buy one get one 50% off, general books",
        "shop_paths": ["/shop/"],
        "product_url_must_contain": "/product/",
        "product_url_skip": ["/product-category/", "/cart"],
        "selectors": {},
        "active": True,
        "notes": "Frequent BOGO promotions.",
    },
]
